export enum TicketErrorCode {
  TICKET_NOT_FOUND = 'TICKET_NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  FORBIDDEN_FIELD_PRIORITY = 'FORBIDDEN_FIELD_PRIORITY',
  FORBIDDEN_FIELD_ASSIGNEDTOID = 'FORBIDDEN_FIELD_ASSIGNEDTOID',
}
