export enum TicketErrorCode {
  TICKET_NOT_FOUND = 'TICKET_NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  FORBIDDEN_FIELD_PRIORITY = 'FORBIDDEN_FIELD_PRIORITY',
  FORBIDDEN_FIELD_ASSIGNED_TO_ID = 'FORBIDDEN_FIELD_ASSIGNED_TO_ID',
  FORBIDDEN_FIELD_STATUS = 'FORBIDDEN_FIELD_STATUS',
  FORBIDDEN_FIELD_TITLE = 'FORBIDDEN_FIELD_TITLE',
  FORBIDDEN_FIELD_DESCRIPTION = 'FORBIDDEN_FIELD_DESCRIPTION',
  FORBIDDEN_FIELD_TEAM_ID = 'FORBIDDEN_FIELD_TEAM_ID',
}
