export enum AuthErrorCode {
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_INACTIVE = "USER_INACTIVE",

  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",

  FORBIDDEN = "FORBIDDEN",
  UNAUTHENTICATED = "UNAUTHENTICATED",

  INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  INVALID_REFRESH_REQUEST = "INVALID_REFRESH_REQUEST",

  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  TOKEN_REVOKED = "TOKEN_REVOKED",

  FORBIDDEN_FIELD_PASSWORD = "FORBIDDEN_FIELD_PASSWORD",
  FORBIDDEN_FIELD_REFRESH_TOKEN = "FORBIDDEN_FIELD_REFRESH_TOKEN",

  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  SESSION_REVOKED = "SESSION_REVOKED",

  ORGANIZATION_ID_REQUIRED = "ORGANIZATION_ID_REQUIRED",
}
