export enum AuthPermission {
  LOGIN = "auth:login",
  LOGOUT = "auth:logout",
  REFRESH = "auth:refresh",
  READ_SESSION = "auth:read_session",
  AUTH_ADMIN_LIST_USERS = "auth_admin:list_users",
  AUTH_LOGIN = "auth:login",
  AUTH_LOGOUT = "auth:logout",
  AUTH_REFRESH = "auth:refresh",
  AUTH_REVOKE = "auth:revoke",
  AUTH_VIEW_PROFILE = "auth:view_profile",
  AUTH_UPDATE_PROFILE = "auth:update_profile",
  SESSION_REVOKE = "auth:session:revoke",
  MANAGE_USERS = "auth_admin:manage_users",
  USER_UPDATE = "auth_admin:user_update",
}
